# Generated by Django 6.0.7 on 2026-07-20 21:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food'), ('shopping', 'Shopping'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('investment', 'Investment'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('freelance', 'Freelance'), ('bonus', 'Bonus'), ('gift', 'Gift'), ('investment', 'Investment'), ('rental', 'Rental'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('goal_completed', 'Goal Completed'), ('reminder', 'Reminder'), ('large_spending', 'Large Spending Alert'), ('monthly_summary', 'Monthly Summary')], default='reminder', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('icon', models.CharField(default='🎯', max_length=8)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('shopping', 'Shopping'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('investment', 'Investment'), ('other', 'Other')], max_length=20)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField(help_text='Any date within the budgeted month; day is ignored.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_budgets', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'category'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
    ]
