# Generated by Django 6.0.7 on 2026-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_invite_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='householdinvite',
            name='unique_pending_invite_per_email',
        ),
        migrations.AddField(
            model_name='householdinvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='householdinvite',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='householdinvite',
            name='status',
        ),
    ]
